{
    "name": "Justech e-CF Admin",
    "version": "19.0.1.3.0",
    "category": "Administration",
    "summary": "Integración Justech e-CF en Administración Justech + asistente y dashboard",
    "author": "Justech",
    "website": "https://justech.do",
    "license": "LGPL-3",
    "depends": [
        "justech_admin_center",
        "justech_fiscal_admin",
        "justech_ecf_core",
        "justech_ecf_xml",
        "justech_ecf_signature",
        "justech_ecf_dgii",
        "justech_ecf_queue",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/ecf_admin_rules.xml",
        "security/ecf_role_bridge.xml",
        "views/ecf_dashboard_views.xml",
        "views/ecf_setup_wizard_views.xml",
        "views/ecf_admin_hub_views.xml",
        "views/ecf_api_inbound_views.xml",
        "data/admin_center_register.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "justech_ecf_admin/static/src/scss/ecf_admin.scss",
        ],
    },
    "installable": True,
    "application": False,
    "justech_admin_center": {
        "product_code": "fiscal",
        "functional_name": "Justech e-CF",
        "short_description": "Facturación electrónica e-CF DGII: certificación, producción (con Gate), XML, firma, colas y recepción.",
        "category": "fiscal",
        "icon": "fa-file-text-o",
        "sequence": 25,
        "activation_scope": "company",
        "fiscal_engine_capable": True,
        "supports_activate": True,
        "supports_deactivate": True,
        "critical": True,
        "open_action_xmlid": "justech_ecf_admin.action_justech_ecf_admin_hub",
    },
}
