{
    "name": "Justech Admin Center",
    "version": "19.0.2.5.0",
    "category": "Administration",
    "summary": "Consola Enterprise Settings → Administración Justech",
    "description": """
Consola Enterprise multiempresa: productos, submódulos, activación por empresa,
reautenticación segura, diagnóstico y auditoría.
    """,
    "author": "Justech",
    "website": "https://justech.do",
    "depends": [
        "base",
        "base_setup",
        "web",
        "mail",
        "justech_modules",
    ],
    "data": [
        "security/justech_admin_center_security.xml",
        "security/ir.model.access.csv",
        "security/justech_admin_center_rules.xml",
        "data/justech_admin_product_data.xml",
        "views/justech_admin_product_views.xml",
        "views/justech_admin_module_views.xml",
        "views/justech_admin_module_company_views.xml",
        "views/justech_admin_operation_views.xml",
        "views/justech_admin_audit_views.xml",
        "views/justech_admin_health_views.xml",
        "views/justech_admin_console_views.xml",
        "views/justech_admin_hub_views.xml",
        "wizards/module_operation_wizard_views.xml",
        "wizards/role_assign_wizard_views.xml",
        "wizards/admin_auth_wizard_views.xml",
        "wizards/company_activation_wizard_views.xml",
        "views/res_users_views.xml",
        "views/res_config_settings_views.xml",
        "views/menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "justech_admin_center/static/src/scss/admin_center.scss",
        ],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
    "license": "LGPL-3",
    "justech_register": {
        "module_code": "justech_admin_center",
        "module_name": "Justech Admin Center",
        "version": "19.0.2.5.0",
        "category": "platform",
        "country": "DO",
        "description": "Consola central Enterprise Justech",
        "dependencies": ["justech_modules"],
        "always_enabled": True,
        "required_module": False,
        "features": [
            {"code": "admin_center", "name": "Administración Justech"},
        ],
    },
    "justech_admin_center": {
        "product_code": "core",
        "functional_name": "Núcleo de administración",
        "short_description": "Consola central del ecosistema Justech",
        "long_description": "Núcleo común: registro modular, seguridad, roles, auditoría y Health Checks. No es una operación comercial por sí solo; normalmente debe permanecer activo.",
        "category": "platform",
        "icon": "fa-th-large",
        "sequence": 1,
        "activation_scope": "global",
        "supports_activate": False,
        "supports_deactivate": False,
        "critical": True,
    },
}
