{
    "name": "Justech Admin Center",
    "version": "19.0.1.0.1",
    "category": "Administration",
    "summary": "Consola central Settings → Administración Justech",
    "description": """
Consola Enterprise para descubrir, instalar, activar/desactivar,
configurar y auditar módulos Justech sin modo desarrollador.
    """,
    "author": "Justech",
    "website": "https://justech.do",
    "depends": [
        "base",
        "base_setup",
        "web",
        "mail",
    ],
    "data": [
        "security/justech_admin_center_security.xml",
        "security/ir.model.access.csv",
        "security/justech_admin_center_rules.xml",
        "views/justech_admin_module_views.xml",
        "views/justech_admin_operation_views.xml",
        "views/justech_admin_audit_views.xml",
        "views/justech_admin_health_views.xml",
        "views/justech_admin_console_views.xml",
        "wizards/module_operation_wizard_views.xml",
        "wizards/role_assign_wizard_views.xml",
        "views/res_users_views.xml",
        "views/res_config_settings_views.xml",
        "views/menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "justech_admin_center/static/src/scss/admin_center.scss",
        ],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
    "license": "LGPL-3",
    "justech_register": {
        "module_code": "justech_admin_center",
        "module_name": "Justech Admin Center",
        "version": "19.0.1.0.1",
        "category": "platform",
        "country": "DO",
        "description": "Central Justech administration console",
        "dependencies": [],
        "always_enabled": True,
        "required_module": False,
        "features": [
            {"code": "admin_center", "name": "Administración Justech"},
        ],
    },
    "justech_admin_center": {
        "functional_name": "Administración Justech",
        "short_description": "Consola central del ecosistema Justech",
        "category": "platform",
        "icon": "fa-th-large",
        "sequence": 1,
        "supports_activate": False,
        "supports_deactivate": False,
        "critical": True,
    },
}
