flowchart LR
    account --> base[justech_l10n_do_base]
    contacts --> base
    l10n_do --> base
    base --> ncf[justech_l10n_do_ncf]
    base --> dash[justech_l10n_do_dashboard]
    ncf --> dash
    account_debit_note --> ncf
    sale --> ncf
