[options]
; Enterprise y custom horneados en imagen hellenia-odoo:19-enterprise (DEV)
addons_path = /opt/odoo/enterprise/addons,/usr/lib/python3/dist-packages/odoo/addons,/opt/odoo/custom
data_dir = /var/lib/odoo
dbfilter = ^hellenia_dev$
list_db = False
log_level = debug
logfile = False
workers = 0
gevent_port = 8072
proxy_mode = True
admin_passwd = CHANGE_ME_ADMIN_PASSWORD
