[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
dbfilter = ^hellenia_dev$
list_db = False
log_level = debug
logfile = False
workers = 0
proxy_mode = True
admin_passwd = CHANGE_ME_ADMIN_PASSWORD
