from . import test_license_service
from . import test_module_registry
from . import test_dependencies
from . import test_multi_company
from . import test_audit_log
from . import test_hardening
from . import test_activation_wizard
from . import test_admin_access
from . import test_commercial_catalog
from . import test_client_module_control
